plug:
  - entity_id: CAB_PRI_relais
    type: zigbee2mqtt_plug_ikea
  - entity_id: CDP_PRI_tele
    type: zigbee2mqtt_plug_ikea
  - entity_id: TER_PRI_guirlande
    type: zigbee2mqtt_plug_ikea
  - entity_id: CDL_PRI_relais
    type: zigbee2mqtt_plug_xiaomi
  - entity_id: CDP_PRI_moustique
    type: zigbee2mqtt_plug_xiaomi
