- name: Create entities files {{ entities_grp }}
  vars:
    data: "{{ item }}"
  template:
    src: "{{ item.type | d(default_template_type[entities_grp])}}.yaml.j2"
    dest: "{{ ha_package_dir }}/{{ entities_grp }}/{{ item.entity_id | lower}}.yaml"
  loop: "{{ lookup('vars',entities_grp) }}"
  notify:
    - restart hass
