- name: Create views for {{ lovelace.key }}
  vars:
    view: "{{ lookup('vars',item) }}"
    view_name: "{{ item }}"
  template:
    src: "{{ lookup('vars',item).template }}.yaml.j2"
    dest: "{{ ha_lovelace_dir }}/{{ lovelace.key }}/{{ item }}.yaml"
  loop: "{{ lovelace.value.views }}"
  notify:
    - restart hass
